//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.DokumentooborotKR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Рас док.
    /// </summary>
    // *** Start programmer edit section *** (РасДок CustomAttributes)

    // *** End programmer edit section *** (РасДок CustomAttributes)
    [AutoAltered()]
    [Caption("Рассмотренный документ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасДокE", new string[] {
            "Дата as \'Дата рассмотрения\'",
            "АвПользователи as \'ID Пользователя\'",
            "АвПользователи.Сотрудники.ФИОСотрудника as \'Утверждающее лицо\'",
            "АвПользователи.Сотрудники.Отделы as \'Утверждающий отдел\'",
            "ФормаДокумента as \'Наименование документа\'",
            "ФормаДокумента.Наименование as \'Наименование документа\'",
            "Утверждение as \'Статус решения\'"}, Hidden=new string[] {
            "ФормаДокумента.Наименование"})]
    [MasterViewDefineAttribute("РасДокE", "АвПользователи", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "IDПользователя")]
    [MasterViewDefineAttribute("РасДокE", "ФормаДокумента", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("РасДокL", new string[] {
            "Дата as \'Дата рассмотрения\'",
            "АвПользователи.Сотрудники.ФИОСотрудника as \'Утверждающее лицо\'",
            "АвПользователи.Сотрудники.Отделы as \'Утверждающий отдел\'",
            "ФормаДокумента.Наименование as \'Наименование документа\'",
            "Утверждение as \'Статус решения\'"})]
    public class РасДок : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private IIS.DokumentooborotKR.Утверждение fУтверждение;
        
        private IIS.DokumentooborotKR.ФормаДокумента fФормаДокумента;
        
        private IIS.DokumentooborotKR.АвПользователи fАвПользователи;
        
        // *** Start programmer edit section *** (РасДок CustomMembers)

        // *** End programmer edit section *** (РасДок CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (РасДок.Дата CustomAttributes)

        // *** End programmer edit section *** (РасДок.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (РасДок.Дата Get start)

                // *** End programmer edit section *** (РасДок.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (РасДок.Дата Get end)

                // *** End programmer edit section *** (РасДок.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасДок.Дата Set start)

                // *** End programmer edit section *** (РасДок.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (РасДок.Дата Set end)

                // *** End programmer edit section *** (РасДок.Дата Set end)
            }
        }
        
        /// <summary>
        /// Утверждение.
        /// </summary>
        // *** Start programmer edit section *** (РасДок.Утверждение CustomAttributes)

        // *** End programmer edit section *** (РасДок.Утверждение CustomAttributes)
        public virtual IIS.DokumentooborotKR.Утверждение Утверждение
        {
            get
            {
                // *** Start programmer edit section *** (РасДок.Утверждение Get start)

                // *** End programmer edit section *** (РасДок.Утверждение Get start)
                IIS.DokumentooborotKR.Утверждение result = this.fУтверждение;
                // *** Start programmer edit section *** (РасДок.Утверждение Get end)

                // *** End programmer edit section *** (РасДок.Утверждение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасДок.Утверждение Set start)

                // *** End programmer edit section *** (РасДок.Утверждение Set start)
                this.fУтверждение = value;
                // *** Start programmer edit section *** (РасДок.Утверждение Set end)

                // *** End programmer edit section *** (РасДок.Утверждение Set end)
            }
        }
        
        /// <summary>
        /// Рас док.
        /// </summary>
        // *** Start programmer edit section *** (РасДок.АвПользователи CustomAttributes)

        // *** End programmer edit section *** (РасДок.АвПользователи CustomAttributes)
        [PropertyStorage(new string[] {
                "АвПользователи"})]
        [NotNull()]
        public virtual IIS.DokumentooborotKR.АвПользователи АвПользователи
        {
            get
            {
                // *** Start programmer edit section *** (РасДок.АвПользователи Get start)

                // *** End programmer edit section *** (РасДок.АвПользователи Get start)
                IIS.DokumentooborotKR.АвПользователи result = this.fАвПользователи;
                // *** Start programmer edit section *** (РасДок.АвПользователи Get end)

                // *** End programmer edit section *** (РасДок.АвПользователи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасДок.АвПользователи Set start)

                // *** End programmer edit section *** (РасДок.АвПользователи Set start)
                this.fАвПользователи = value;
                // *** Start programmer edit section *** (РасДок.АвПользователи Set end)

                // *** End programmer edit section *** (РасДок.АвПользователи Set end)
            }
        }
        
        /// <summary>
        /// Рас док.
        /// </summary>
        // *** Start programmer edit section *** (РасДок.ФормаДокумента CustomAttributes)

        // *** End programmer edit section *** (РасДок.ФормаДокумента CustomAttributes)
        [PropertyStorage(new string[] {
                "ФормаДокумента"})]
        [NotNull()]
        public virtual IIS.DokumentooborotKR.ФормаДокумента ФормаДокумента
        {
            get
            {
                // *** Start programmer edit section *** (РасДок.ФормаДокумента Get start)

                // *** End programmer edit section *** (РасДок.ФормаДокумента Get start)
                IIS.DokumentooborotKR.ФормаДокумента result = this.fФормаДокумента;
                // *** Start programmer edit section *** (РасДок.ФормаДокумента Get end)

                // *** End programmer edit section *** (РасДок.ФормаДокумента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасДок.ФормаДокумента Set start)

                // *** End programmer edit section *** (РасДок.ФормаДокумента Set start)
                this.fФормаДокумента = value;
                // *** Start programmer edit section *** (РасДок.ФормаДокумента Set end)

                // *** End programmer edit section *** (РасДок.ФормаДокумента Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасДокE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасДокE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасДокE", typeof(IIS.DokumentooborotKR.РасДок));
                }
            }
            
            /// <summary>
            /// "РасДокL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасДокL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасДокL", typeof(IIS.DokumentooborotKR.РасДок));
                }
            }
        }
    }
}
