//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.DokumentooborotKR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Форма документа.
    /// </summary>
    // *** Start programmer edit section *** (ФормаДокумента CustomAttributes)

    // *** End programmer edit section *** (ФормаДокумента CustomAttributes)
    [AutoAltered()]
    [Caption("Форма документа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФормаДокументаE", new string[] {
            "Дата as \'Дата составления\'",
            "АвПользователи as \'ID Пользователя\'",
            "АвПользователи.Сотрудники.ФИОСотрудника as \'Ответственный документа\'",
            "АвПользователи.Сотрудники.Отделы as \'Отдел отправителя\'",
            "Наименование as \'Наименование документа\'",
            "Содержание as \'Содержание документа\'",
            "Отделы as \'Отдел получателя\'"})]
    [MasterViewDefineAttribute("ФормаДокументаE", "АвПользователи", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "IDПользователя")]
    [View("ФормаДокументаL", new string[] {
            "Дата as \'Дата составления\'",
            "АвПользователи.Сотрудники.ФИОСотрудника as \'Ответственный документа\'",
            "АвПользователи.Сотрудники.Отделы as \'Отдел отправителя\'",
            "Наименование as \'Наименование документа\'",
            "Содержание as \'Содержание документа\'",
            "Отделы as \'Отдел получателя\'"})]
    public class ФормаДокумента : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private string fСодержание;
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private IIS.DokumentooborotKR.Отделы fОтделы;
        
        private IIS.DokumentooborotKR.АвПользователи fАвПользователи;
        
        // *** Start programmer edit section *** (ФормаДокумента CustomMembers)

        // *** End programmer edit section *** (ФормаДокумента CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ФормаДокумента.Дата CustomAttributes)

        // *** End programmer edit section *** (ФормаДокумента.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ФормаДокумента.Дата Get start)

                // *** End programmer edit section *** (ФормаДокумента.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ФормаДокумента.Дата Get end)

                // *** End programmer edit section *** (ФормаДокумента.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаДокумента.Дата Set start)

                // *** End programmer edit section *** (ФормаДокумента.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ФормаДокумента.Дата Set end)

                // *** End programmer edit section *** (ФормаДокумента.Дата Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ФормаДокумента.Наименование CustomAttributes)

        // *** End programmer edit section *** (ФормаДокумента.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ФормаДокумента.Наименование Get start)

                // *** End programmer edit section *** (ФормаДокумента.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ФормаДокумента.Наименование Get end)

                // *** End programmer edit section *** (ФормаДокумента.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаДокумента.Наименование Set start)

                // *** End programmer edit section *** (ФормаДокумента.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ФормаДокумента.Наименование Set end)

                // *** End programmer edit section *** (ФормаДокумента.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Отделы.
        /// </summary>
        // *** Start programmer edit section *** (ФормаДокумента.Отделы CustomAttributes)

        // *** End programmer edit section *** (ФормаДокумента.Отделы CustomAttributes)
        public virtual IIS.DokumentooborotKR.Отделы Отделы
        {
            get
            {
                // *** Start programmer edit section *** (ФормаДокумента.Отделы Get start)

                // *** End programmer edit section *** (ФормаДокумента.Отделы Get start)
                IIS.DokumentooborotKR.Отделы result = this.fОтделы;
                // *** Start programmer edit section *** (ФормаДокумента.Отделы Get end)

                // *** End programmer edit section *** (ФормаДокумента.Отделы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаДокумента.Отделы Set start)

                // *** End programmer edit section *** (ФормаДокумента.Отделы Set start)
                this.fОтделы = value;
                // *** Start programmer edit section *** (ФормаДокумента.Отделы Set end)

                // *** End programmer edit section *** (ФормаДокумента.Отделы Set end)
            }
        }
        
        /// <summary>
        /// Содержание.
        /// </summary>
        // *** Start programmer edit section *** (ФормаДокумента.Содержание CustomAttributes)

        // *** End programmer edit section *** (ФормаДокумента.Содержание CustomAttributes)
        [StrLen(255)]
        public virtual string Содержание
        {
            get
            {
                // *** Start programmer edit section *** (ФормаДокумента.Содержание Get start)

                // *** End programmer edit section *** (ФормаДокумента.Содержание Get start)
                string result = this.fСодержание;
                // *** Start programmer edit section *** (ФормаДокумента.Содержание Get end)

                // *** End programmer edit section *** (ФормаДокумента.Содержание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаДокумента.Содержание Set start)

                // *** End programmer edit section *** (ФормаДокумента.Содержание Set start)
                this.fСодержание = value;
                // *** Start programmer edit section *** (ФормаДокумента.Содержание Set end)

                // *** End programmer edit section *** (ФормаДокумента.Содержание Set end)
            }
        }
        
        /// <summary>
        /// Форма документа.
        /// </summary>
        // *** Start programmer edit section *** (ФормаДокумента.АвПользователи CustomAttributes)

        // *** End programmer edit section *** (ФормаДокумента.АвПользователи CustomAttributes)
        [PropertyStorage(new string[] {
                "АвПользователи"})]
        [NotNull()]
        public virtual IIS.DokumentooborotKR.АвПользователи АвПользователи
        {
            get
            {
                // *** Start programmer edit section *** (ФормаДокумента.АвПользователи Get start)

                // *** End programmer edit section *** (ФормаДокумента.АвПользователи Get start)
                IIS.DokumentooborotKR.АвПользователи result = this.fАвПользователи;
                // *** Start programmer edit section *** (ФормаДокумента.АвПользователи Get end)

                // *** End programmer edit section *** (ФормаДокумента.АвПользователи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаДокумента.АвПользователи Set start)

                // *** End programmer edit section *** (ФормаДокумента.АвПользователи Set start)
                this.fАвПользователи = value;
                // *** Start programmer edit section *** (ФормаДокумента.АвПользователи Set end)

                // *** End programmer edit section *** (ФормаДокумента.АвПользователи Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФормаДокументаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормаДокументаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормаДокументаE", typeof(IIS.DokumentooborotKR.ФормаДокумента));
                }
            }
            
            /// <summary>
            /// "ФормаДокументаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормаДокументаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормаДокументаL", typeof(IIS.DokumentooborotKR.ФормаДокумента));
                }
            }
        }
    }
}
